-- ==============================================================
-- FerramentasWeb • Schema Supabase para Clientes & Leads MeliSpy
-- ==============================================================
-- Execute este script no SQL Editor do seu projeto Supabase (supabase.com)

create table if not exists public.clientes_melispy (
  id bigint generated by default as identity primary key,
  nome text,
  email text,
  whatsapp text,
  plano text default 'starter',
  hwid text,
  license_key text,
  payment_id text,
  status text default 'ativo', -- 'lead', 'iniciou_checkout', 'ativo'
  origem text default 'checkout',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security)
alter table public.clientes_melispy enable row level security;

-- Política 1: Permitir que novos clientes/leads se cadastrem livremente
create policy "Permitir cadastro de clientes"
  on public.clientes_melispy for insert
  with check (true);

-- Política 2: Permitir leitura das licenças
create policy "Permitir leitura de clientes"
  on public.clientes_melispy for select
  using (true);
